main: me.dkim19375.magicitems.MagicItems
name: MagicItems
version: ${pluginVersion}
description: Get some OP items with one command!
author: dkim19375
api-version: 1.13
website: https://www.spigotmc.org/resources/magicitems.82693/updates
commands:
  magicitems:
    description: main command
    permission: magicitems.command
    aliases: mi
    usage: /magicitems help
permissions:
  magicitems.reload:
    description: Reload the config files
  magicitems.give:
    description: Able to give items
  magicitems.version:
    description: Get version and check updates
  magicitems.enchants:
    description: Can use /magicitems enchants
  magicitems.attributes:
    description: Can use /magicitems attibutes
  magicitems.vanishing:
    description: Can use /magicitems vanishing
  magicitems.binding:
    description: Can use /magicitems binding